### ISSUE TITLE
License problem.

### ISSUE THREAD

**Issue by pppkin** [JaapWijnen/metal-raytracing#1]
Hi! AWESOME WORK! This project is really great for education/demonstration/prototype purpose but currently it lacks license info, could you please clarify what license is this published under?

**Comment by JaapWijnen** [comment]
Thanks! Any license that you'd prefer in this case?

**Comment by pppkin** [comment]
I believe [MIT](https://choosealicense.com/licenses/mit/) or [Apache-2.0](https://choosealicense.com/licenses/apache-2.0/) would work best for a project like this:)

**Comment by JaapWijnen** [comment]
all done!
